spring.datasource.url=jdbc:postgresql://localhost:5432/simulator_db
spring.datasource.username=simulator_user
spring.datasource.password=Admin123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


# -------------------------
# Logging configuration
# -------------------------

# Log file location and name
logging.file.name=D:\Simulator.log


# Log pattern (file)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

# Log pattern (console)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n


# Default log level
logging.level.root=INFO

# Your application logs (more detail)
logging.level.com.example.simulator=DEBUG

